version: "3.8"

services:
    mongo:
        image: mongo:6.0
        container_name: mongo-v3
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./mongo-data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        networks:
            - iot_net

    spark-master:
        build:
            context: .
            dockerfile: spark.Dockerfile
        container_name: spark-master-v3
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
            - MONGO_URI=mongodb://mongo:27017
        ports:
            - "8080:8080"
            - "7077:7077"
        volumes:
            - ./ex:/app/ex
            - ./demo:/app/demo
            - ./logs:/app/logs
        networks:
            - iot_net

    spark-worker:
        build:
            context: .
            dockerfile: spark.Dockerfile
        container_name: spark-worker-v3
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark-master:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - MONGO_URI=mongodb://mongo:27017
        depends_on:
            - spark-master
        ports:
            - "8081:8081"
        volumes:
            - ./ex:/app/ex
            - ./demo:/app/demo
            - ./logs:/app/logs
        networks:
            - iot_net

networks:
    iot_net:
        name: IoT-Spark
        driver: bridge
